### ISSUE TITLE
Implement TCP cross-server RPC instead of ZMQ

### ISSUE THREAD

**Issue by tshemsedinov** [tshemsedinov/impress#321]

**Comment by itadapter** [comment]
I was waiting for this day.....
NOW, you have cracked opened a huge chasm.....
 dont forget to:
a. Manage channels
   1. Close sockets after X secs of inactivity
   2. Do NOT open new sockets to PEER X, first try to acquire transport for Y ms
   3. Do not apply rule 2 if there more than Z transports already open
...I have only scratched the surface.
Why? Imagine a cluster with 32 DB shards. (that is very realistic).
You are on a web server A, you need to send queries to 32 shards, that is 32 channels for 1 thread.
Imagine a user needs to push 4 mbyte zip file to storage, that means that your channel is busy for the duration of the send.
Dont give that "Node don't use threads". OS is based on processes threads, so the channel needs to be multiplexing one, otherwise you can quickly run-out of channel numbers.

b. How are you going to monitor /see what is going on between say 32 computers?
Not saying that ZeroMQ helps with it... noone does

have fun

**Comment by tshemsedinov** [comment]
After solving a few applied tasks I understood that ZMQ gives me less then TCP ))) It have aditional restrictions and pattern limitations but it don't solve any of mentioned problems and not good for RPC
