### ISSUE TITLE
Change and test deploy scripts

### ISSUE THREAD

**Issue by tshemsedinov** [tshemsedinov/impress#478]
I changed deploy scripts to install ```node.js``` from binaries, see: https://github.com/tshemsedinov/impress/commit/baaf05d7b5b820ef73a5574928d830464861fe7e and to install latest ```MongoDB``` server (3.x), see: https://github.com/tshemsedinov/impress/commit/582398cbd114cedb597849ac616c06f105501aeb
Old scripts (installing node from source) renamed to ```*-src.sh``` I also fixed a bug in those old scripts because latest node.js requires new C++ compiler included in ```devtoolset-2``` (just for 32bit CentOS). But we need to test all scripts once more and before that we need to change all scripts to install latest MongoDB as I did for CentOS 7.

**Comment by johnbizokk** [comment]
In commit https://github.com/tshemsedinov/impress/commit/80c0d00d5889898606d3cfe43b7376d1a6106101, added: 
- Mongodb 3.2 support 
- Node 5.x support to install from sources

Tested all scripts in empty droplets:
- Ubuntu 12.04 x64 +
- Ubuntu 14.04 x64 +
- Debian 7.9 x64 +
- CentOS 7.1 x64 +
- CentOS 6.7 x64 +
- CentOS 6.7 x32 -

Also, problem is detected with scripts, on x32 system:
- [centos6x32-src.sh](https://github.com/tshemsedinov/impress/blob/master/deploy/centos6x32-src.sh) 
- [centos6x32.sh](https://github.com/tshemsedinov/impress/blob/master/deploy/centos6x32.sh)

Mongodb is [no longer](https://docs.mongodb.org/manual/release-notes/3.0-compatibility/#compatibility-platform-support) provided support on 32-bit platform for Linux RPM and DEB packages, but, however, supports install from [binary archives](https://docs.mongodb.org/manual/tutorial/install-mongodb-on-linux/). 

Node install from nodesource  [not available for CentOS 6 x32](https://github.com/nodesource/distributions#rpm), instead of [info](https://nodejs.org/en/download/package-manager/#enterprise-linux-and-fedora) on nodejs.org, while install, get message - 
`## Your distribution, identified as "centos-release-6-7.el6.centos.12.3.i686", is not currently supported, please contact NodeSource at https://github.com/nodesource/distributions/issues if you think this is incorrect or would like your distribution to be considered for support
`

Also, when compile node 5.x from sources, appear problem with the launch of impress.

**Comment by johnbizokk** [comment]
In  #488, added:

- Debian 8.3 support 
- Ubuntu 15.10 support

Tested deploy scripts in empty droplets:

- [x] Debian 7.9 x64
- [x] Debian 8.3 x64
- [x] Ubuntu 12.04.5 x64
- [x] Ubuntu 14.04.4 x64
- [x] Ubuntu 15.10 x64
